### PR TITLE
Make deployable via GitHub pages

### PR DESCRIPTION
**Pull request by tkw1536**
Looking at this repository, a multitude of dependencies (node, ruby, a lot of npm modules) need to be installed to be able to compile this page. Furthermore, a hacked post-commit hook on travis is used to deploy the page to our own server. 

This PR makes minor changes to the repository and turns it into a Jekyll site, allowing it to be hosted on [GitHub pages](https://pages.github.com). The resulting page is functionally identical to the old one, however it does not support minimisation. 
This PR intentionally **does not** break the existing deployment mechanism, so we can think about which static page generator we want to actually use.

### CODE REVIEW

**Comment by tkw1536** [comment]
@ngetahun @shvmgrx I would like to hear your thoughts about moving the hosting to GitHub pages. As stated, that would save us from having to maintain the post-deploy hook. This might come in handy if we ever choose to change the droplet provider in the future.

**Comment by shvmgrx** [comment]
Yeah...that sounds good to me..@tkw1536

**Comment by ngetahun** [comment]
@tkw1536 we need to update the domain so that it points to github servers. And also can we setup a QA site like 2017f.jacobshack.com with github-pages.

**Comment by tkw1536** [comment]
Yes, either can be achieved from the GitHub side by adding a CNAME file to the repository. 
DNS setup should be two `A` records for the TLD, or a `CNAME` record for the subdomain, see [Github documentation](https://help.github.com/articles/using-a-custom-domain-with-github-pages/). 
Unfortunately, if we want to have both, we need to have two repositories. 
I don't quite see the difference between the main site and the QA sites? What is the reason for having both?

Speaking of domain setup, I believe the mail interface is still broken, that should be fixed (separately from this issue) as well.

**Comment by ngetahun** [comment]
The QA site helps to experiment with different layouts and that's what we did last year. I don't want another repo for the QA site. For the time being, we can use github pages for the main site [jacobshack.com] (https://jacobshack.com) and use the droplet for the QA site. I will edit the travis.yml and change it to deploy the Jekyll site. 
The mail client was working but I think the problem is with nginx configuration. I've tried to fix it but there were problems. @kuboschek can you shed some light on this matter?

**Pull request merged**
